#!/bin/bash

echo "🔗 Guía para obtener MongoDB Atlas Connection String"
echo "=================================================="
echo ""
echo "1️⃣ En tu MongoDB Atlas Dashboard:"
echo "   - Haz clic en 'Get connection string' (botón verde que viste)"
echo "   - O ve a: Database → Connect → Drivers"
echo ""
echo "2️⃣ Selecciona 'Node.js' como driver"
echo ""
echo "3️⃣ Copia la connection string que se ve así:"
echo "   mongodb+srv://<username>:<password>@cluster0.xxxxx.mongodb.net/<database>?retryWrites=true&w=majority"
echo ""
echo "4️⃣ Reemplaza:"
echo "   - <username> con tu usuario de Atlas"
echo "   - <password> con tu contraseña de Atlas"
echo "   - <database> con 'my-app' (tu base de datos actual)"
echo ""
echo "5️⃣ El resultado final será algo como:"
echo "   mongodb+srv://tuusuario:tupassword@cluster0.xxxxx.mongodb.net/my-app?retryWrites=true&w=majority"
echo ""
echo "💡 Consejo: Guarda esta cadena, la necesitarás para Vercel"
echo ""
echo "🔒 Seguridad: Asegúrate de que tu cluster permite conexiones desde:"
echo "   - IP Address: 0.0.0.0/0 (cualquier IP) para Vercel"
echo "   - O específicamente desde las IPs de Vercel"
